# Generated by Django 4.1.7 on 2024-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sales_number',
            field=models.IntegerField(default=0),
        ),
    ]
