# Generated by Django 4.1.7 on 2024-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_sales_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
