# Generated by Django 4.1.13 on 2024-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feature_product_related_products_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features_ar',
            field=models.ManyToManyField(null=True, to='home.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_en',
            field=models.ManyToManyField(null=True, to='home.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_fa',
            field=models.ManyToManyField(null=True, to='home.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_ka',
            field=models.ManyToManyField(null=True, to='home.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ka',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
