# Generated by Django 4.1.7 on 2024-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_category_name_ar_category_name_en_category_name_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/%y/%m/%d/'),
        ),
    ]
